name: bradley
on: 
  push: 
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install 
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Move files
        run: |
          mv WeatherApp/dist/index.html WeatherApp
          mv WeatherApp/dist/main.js WeatherApp

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: .